heat_template_version: 2015-04-30

parameters:
    keyname:
        type: string
        description: keyname
        default: mykey

resources:
    keypair:
        type: OS::Nova::KeyPair
        properties:
            name: { get_param: keyname }
            public_key: { get_file: id_rsa.pub }

outputs:
    mykey:
        description: output mykey
        value: { get_resource: keypair }
